version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: docker/prod/Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/opt/wedding_house_project/backend/static
      - media_volume:/opt/wedding_house_project/backend/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      #Database will be remove, if is a docker create volume.
      #Switch to local folder ./
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/opt/wedding_house_project/backend/static
      - media_volume:/opt/wedding_house_project/backend/media
    ports:
      - 80:80
    depends_on:
      - webapp

volumes:
  #postgres_data:
  static_volume:
  media_volume:
