# Generated by Django 3.0.7 on 2020-07-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheongsammodels',
            name='sku',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
