# Generated by Django 3.1.1 on 2020-10-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201013_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheongsamModels',
            new_name='CheongsamModel',
        ),
        migrations.RenameModel(
            old_name='TeasetModels',
            new_name='TeasetModel',
        ),
    ]
